logging:
  level:
    ROOT: INFO
    org.springframework.web: ERROR
    com.rdas: DEBUG
    org.hibernate: ERROR

server:
  port: 8080
  servlet:
    context-path: /hazspring


hazelcast:
  port: 21412
